version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ate_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/01_init_schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
      - ./database/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
      - postgres_ate_data:/var/lib/postgresql/data

volumes:
  postgres_ate_data:
